-- supabase/migrations/001_init.sql
-- SignalReach AI — Initial Database Schema
-- Run via: supabase db push
-- Or paste directly into Supabase SQL Editor

-- ─────────────────────────────────────────────
-- EXTENSIONS
-- ─────────────────────────────────────────────
create extension if not exists "uuid-ossp";

-- ─────────────────────────────────────────────
-- TABLES
-- ─────────────────────────────────────────────

-- Companies being tracked
create table if not exists companies (
  id          uuid primary key default uuid_generate_v4(),
  name        text not null,
  domain      text,
  industry    text,
  stage       text,           -- e.g. 'Seed', 'Series A', 'Series B'
  added_by    uuid,           -- future: references auth.users(id)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Ensure the UNIQUE constraint exists for ON CONFLICT (name)
-- (This is the fix for error 42P10)
create unique index if not exists companies_name_uniq
on companies (name);

-- Add missing columns if they don't exist (safe if you modify earlier migrations)
alter table companies add column if not exists industry text;
alter table companies add column if not exists stage text;
alter table companies add column if not exists domain text;

-- Cached signal data per company (avoids re-scraping every request)
create table if not exists signals (
  id           uuid primary key default uuid_generate_v4(),
  company_id   uuid not null references companies(id) on delete cascade,
  signal_type  text not null check (signal_type in ('job', 'reddit', 'news')),
  source       text not null,   -- e.g. 'LinkedIn', 'r/sysadmin', 'TechCrunch'
  title        text not null,
  body         text,
  raw_json     jsonb,            -- full original payload for debugging
  fetched_at   timestamptz not null default now(),
  expires_at   timestamptz not null default (now() + interval '24 hours')
);

-- Intent scores calculated by Gemini
create table if not exists intent_scores (
  id           uuid primary key default uuid_generate_v4(),
  company_id   uuid not null references companies(id) on delete cascade,
  score        integer not null check (score between 0 and 100),
  reasoning    text,
  key_signals  text[],           -- array of short signal descriptions
  scored_at    timestamptz not null default now()
);

-- Outreach email drafts generated by Gemini
create table if not exists outreach_drafts (
  id              uuid primary key default uuid_generate_v4(),
  company_id      uuid not null references companies(id) on delete cascade,
  intent_score_id uuid references intent_scores(id),
  recipient_name  text not null,
  recipient_email text,
  subject         text not null,
  body            text not null,
  status          text not null default 'draft' check (status in ('draft', 'sent', 'replied', 'archived')),
  created_at      timestamptz not null default now(),
  sent_at         timestamptz
);

alter table outreach_drafts add column if not exists created_at timestamptz not null default now();

-- ─────────────────────────────────────────────
-- INDEXES (for fast queries in the dashboard)
-- ─────────────────────────────────────────────
create index if not exists idx_signals_company_id    on signals(company_id);
create index if not exists idx_signals_type          on signals(signal_type);
create index if not exists idx_signals_expires       on signals(expires_at);

create index if not exists idx_intent_scores_company on intent_scores(company_id);
create index if not exists idx_intent_scores_score   on intent_scores(score desc);

create index if not exists idx_outreach_company      on outreach_drafts(company_id);
create index if not exists idx_outreach_status       on outreach_drafts(status);

-- ─────────────────────────────────────────────
-- VIEWS (convenient for dashboard queries)
-- ─────────────────────────────────────────────

-- HAPUS VIEW LAMA AGAR TIDAK BENTROK TIPE DATA (FIX ERROR 42P16)
drop view if exists dashboard_leads;
drop view if exists latest_scores;

-- Get the latest intent score per company
create or replace view latest_scores as
  select distinct on (company_id)
    company_id,
    score,
    reasoning,
    key_signals,
    scored_at
  from intent_scores
  order by company_id, scored_at desc;

-- Dashboard: companies with their latest score, sorted by score
create or replace view dashboard_leads as
  select
    c.id                                                               as company_id,
    c.name                                                             as company_name,
    c.domain,
    c.industry,
    c.stage,
    ls.score                                                           as intent_score,
    ls.key_signals,
    ls.scored_at,
    (select count(*)::int
       from outreach_drafts od
      where od.company_id = c.id and od.status = 'draft')  as draft_count,
    (select count(*)::int
       from outreach_drafts od
      where od.company_id = c.id and od.status = 'sent')   as sent_count
  from companies c
  left join latest_scores ls on ls.company_id = c.id
  order by ls.score desc nulls last;

-- ─────────────────────────────────────────────
-- ROW LEVEL SECURITY (basic setup, expand later)
-- ─────────────────────────────────────────────
alter table companies       enable row level security;
alter table signals         enable row level security;
alter table intent_scores   enable row level security;
alter table outreach_drafts enable row level security;

-- For hackathon: allow all authenticated users to read/write everything
-- Tighten this per-user in production
drop policy if exists "Allow all for authenticated users" on companies;
create policy "Allow all for authenticated users"
  on companies
  for all
  using (auth.role() = 'authenticated');

drop policy if exists "Allow all for authenticated users" on signals;
create policy "Allow all for authenticated users"
  on signals
  for all
  using (auth.role() = 'authenticated');

drop policy if exists "Allow all for authenticated users" on intent_scores;
create policy "Allow all for authenticated users"
  on intent_scores
  for all
  using (auth.role() = 'authenticated');

drop policy if exists "Allow all for authenticated users" on outreach_drafts;
create policy "Allow all for authenticated users"
  on outreach_drafts
  for all
  using (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────
-- SEED DATA (for demo / hackathon)
-- ─────────────────────────────────────────────
insert into companies (name, domain, industry, stage) values
  ('Acme Corp',   'acmecorp.io',   'SaaS',        'Series B'),
  ('Nexus AI',    'nexus.ai',      'ML Platform',  'Seed'),
  ('Buildify Inc','buildify.dev',  'DevTools',     'Growth'),
  ('Dataloop',    'dataloop.io',   'Analytics',    'Series A'),
  ('Pylon Systems','pylonsys.com', 'Infra',        'Series C')
on conflict (name) do nothing;

-- Seed intent scores using subqueries
insert into intent_scores (company_id, score, reasoning, key_signals)
select id, 92, 'Company is actively hiring for legacy systems overhaul, and public complaints confirm internal tool frustration post Series B.', array['Hiring Head of IT Infrastructure', 'CRM complaint on r/sysadmin', 'Series B funding secured']
from companies where name = 'Acme Corp'
on conflict do nothing;

insert into intent_scores (company_id, score, reasoning, key_signals)
select id, 88, 'Strong hiring signals for LLM pipelines coupled with significant scaling bottlenecks reported on ML communities.', array['Hiring ML Infrastructure Engineer', 'LLM pipeline issues on r/MachineLearning', 'Raised $12M Seed funding']
from companies where name = 'Nexus AI'
on conflict do nothing;

insert into intent_scores (company_id, score, reasoning, key_signals)
select id, 85, 'SDK integration is broken and driving developers to seek alternatives, creating an urgent window.', array['Developer complaints on r/webdev', 'SDK webhooks broken for 3 weeks', 'Hits 50k developers milestone']
from companies where name = 'Buildify Inc'
on conflict do nothing;

insert into intent_scores (company_id, score, reasoning, key_signals)
select id, 79, 'Frequent pipeline outages leading to high customer dissatisfaction despite a recent successful funding round.', array['Frequent outages reported on r/dataengineering', 'ARR and scale expansion', 'Closes $20M Series A']
from companies where name = 'Dataloop'
on conflict do nothing;

insert into intent_scores (company_id, score, reasoning, key_signals)
select id, 65, 'Stable infra ARR growth but high subscription price increases are leading customers to evaluate alternatives.', array['Pricing complaints on r/sysadmin', 'ARR growth but support struggles', 'Series C infrastructure company']
from companies where name = 'Pylon Systems'
on conflict do nothing;